[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1WXlFzz9708YhA1QSHkei_ENFqJFgdi9Ng4uY8FtVQdE/edit?usp=sharing"
type = "service_account"
project_id = "sql-data-project-385809"
private_key_id = "18efc07d1ba709fdea59a10eb319547ded03c344"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC6smUgfQoSasWz
SEc4wWmenG3H2mlR94W0cEoS5A5hGVMfnQhcxcCUN4xZUMzkrOj6YYVqXDS4Ad+a
uxzYXxQLmyLDL7SUHaGg7/+TFYvpe+vbhbIpKuUkvOS1EXSwYq1BPV3p3KWU7er8
q4aTkgvSnzs1iiQ/nZXOiPVrP5NL5KCt7IWom9LC4iNECZ/uO87UK4hTiglgpOgh
QUGjiTB228JQRZfspRe3A71SObPUV/DhpIKqpCZr4ibMONTJ6jyChqIHBVBDzaxB
m8oWbzG9/7yQok9Gvv2J7RqqXQ8BbMYlDuCQHb7auRlRZiYWAJsdhki39hJghA9p
jt5kb9XLAgMBAAECggEAI8wM49vV0I40dhnHvjQnokfwLL/OLe897ckSCuk7cJbA
f3FGpzMrp7+243FAuCAHU+ra//fKC/Yf/7Uc5MfmOgt28OH2x+eelBMwd+1LtGsU
YDUUYhxdb1vgpm9AZomlGrs/hJXQEexEgEoLNcRtC+eIHM3uAVyf2sgb9oJsJcLO
t0hGor/63DXNp+eUfmfiToPu7Uxk11XRy2MvP8uP1vVYB2J86dNftioYSSFik+fX
9X9bzFcUmFuGlLO0VwK2/H+29zN3DYARTFsHfa5JzedwH3NUFWoLeVAO9maGxHpp
wBlUIPs6MUkH+VNhrh0Ksg6IHxh7/srfWaGwHWfz8QKBgQDk6wPTjDleLYm3EwXr
MUU0Hp0DjTuRVZWYQqmKveCSaf8z3BETlMItO6tjTvGtHC4e5YjQbnGouLgkEMyz
zaWXWwZSob6Pv/oCjCtNKTHeutX2DE0YO+JyrL1svQ7gFuMLRPEf6V7QDNr+NnYD
FIAVKH8qBikikPiDF+/PNO6LPQKBgQDQyKyuI0IHymwlV5MerNIVGUEnz3zqTB2s
AoJ5MH2OuDXZXm/V3g2qr0x8VfWa9rK5y7eZtn7T7W1C5pC8vQ0mk3X4y0rxjVaZ
xNWUQlG/eKVlE+3QZBcTIMAyInzk0k++0TjsuyGiO+9wAqBg6FkGZ0Bc4PiC9IYV
3P0Fq3MVpwKBgFwvqGLQ3WlnvUXUi1WjidLrYR/FCHAGny+p6MzOmllcBkHEJbxU
871zghmD+R9Vcd1PYkFNuMfRW5ZqjYT7E+xX47vzFuKc1PmhqO5x4HtpkjB707Am
rZKwrbfUiuEDVnt7T/8h4+S0yJwHIo8q+kmK/WrXAEnDR9DDGve+wTGhAoGBAMl9
EOERV7ULDilPhcSxxiDkeXPBEu1OPch1t5LbUCC++ADp2YYNQSU6/dZ0Yo2FjWAv
EOYAMA+4b5yDxKTQ0fMrlktfbdkFrNDDG9dz1U6yUPPmMrjND1O/ZJw9mkh+CsW9
RnF3+vKFYwK3Fi3PrbK3TG8WEd7Xuts4pNqm5m67AoGBAMGbWUmLcR+nxKs61/TY
aGIc+/oVs7zSinl0ZWxTJugJg7efDpaJ8uECuNqrYJvzHquystgOkAYcF06My3XC
13E9TRGA83mxnnH+BWhzOQaA9TUUr5poeNb+chCPgQ33ci+usGRVbsLtiklbvIwS
xiCWqosmMP7c2bDhWR2IFBFN
-----END PRIVATE KEY-----
"""
client_email = "factoring-law-sim@sql-data-project-385809.iam.gserviceaccount.com"
client_id = "116759694530733461022"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/factoring-law-sim%40sql-data-project-385809.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
